name: golangci-lint
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'feature-*'
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.24'
        include:
          - go-version: '1.23'
            golangci-lint: true
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - uses: actions/checkout@v4

      - name: Switch Dubbo-go version
        run: |
          # Acquire information of branch
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            BRANCH=${{github.base_ref}}
          elif [ "$GITHUB_EVENT_NAME" == "push" ]; then
            BRANCH=$GITHUB_REF_NAME
          else
            echo "$GITHUB_EVENT_NAME event is unsupported right now"
            exit 1
          fi
          echo "EVENT = $GITHUB_EVENT_NAME, BRANCH = $BRANCH"
          # Edit the version
          go mod edit -replace=dubbo.apache.org/dubbo-go/v3=dubbo.apache.org/dubbo-go/v3@$BRANCH
          go mod tidy

      - name: golangci-lint
        if: matrix.golangci-lint == true
        uses: golangci/golangci-lint-action@v6
        with:
          # Use latest version that supports Go 1.23
          version: latest
          args: --timeout=10m
      
      - name: Build test (for Go 1.24)
        if: matrix.go-version == '1.24'
        run: go build ./...
